### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by egy1337** [MapsIndoors/MapsIndoorsWeb#2]
Hello , How i can solve this ?

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path c:\wamp64\www\maps\modules\sdk\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'c:\wamp64\www\maps\modules\sdk\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2020-11-17T06_44_26_352Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! maps-indoors-webapp@3.12.5 start: `npm run build:dev --prefix ./modules/sdk && ng serve`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the maps-indoors-webapp@3.12.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2020-11-17T06_44_26_407Z-debug.log

**Comment by ammapspeople** [comment]
Hi,

Thanks for reaching out!

There are some dependency errors in the current version.

Until we make an official fix, try this:

1) in the `package.json` file, replace the line
`"start": "npm run build:dev --prefix ./modules/sdk && ng serve",`
with
`"start": "ng serve",`

2) install a specific version of the typescript dependency by running `npm install typescript@3.2.4`

3) replace the entire content of the file `src/app/app.error-handler.ts` with this:

```
import { ErrorHandler } from '@angular/core';

export function errorHandlerFactory():ErrorHandler {
    return new ErrorHandler();
}
```

Now try running `npm start` again.

Let us know how that works out for you.
