### ISSUE TITLE
Direction Service still has access to googleMap 

### ISSUE THREAD

**Issue by jain-akshat-28** [MapsIndoors/MapsIndoorsWeb#3]
Direction Service still has access to googleMap which is replaced by map and hence not able to start the application.

**Error Log**

ERROR in node_modules/@sentry/hub/dist/session.d.ts(17,27): error TS2304: Cannot find name 'Omit'.
node_modules/@sentry/types/dist/misc.d.ts(50,61): error TS2304: Cannot find name 'bigint'.
node_modules/@types/node/globals.d.ts(712,19): error TS2304: Cannot find name 'bigint'.
node_modules/@types/node/globals.d.ts(1020,11): error TS2304: Cannot find name 'BigUint64Array'.
node_modules/@types/node/globals.d.ts(1021,11): error TS2304: Cannot find name 'BigInt64Array'.
node_modules/@types/node/ts3.6/base.d.ts(13,21): error TS2727: Cannot find lib definition for 'esnext.bigint'. Did you mean 'esnext.intl'?
node_modules/@types/node/util.d.ts(118,56): error TS2304: Cannot find name 'BigInt64Array'.
node_modules/@types/node/util.d.ts(119,57): error TS2304: Cannot find name 'BigUint64Array'.
node_modules/@types/node/util.d.ts(121,77): error TS2304: Cannot find name 'BigInt'.
src/app/services/direction.service.ts(106,41): error TS2339: Property 'googleMap' does not exist on type 'GoogleMapService'.
src/app/services/direction.service.ts(113,73): error TS2339: Property 'googleMap' does not exist on type 'GoogleMapService'.
src/app/services/direction.service.ts(144,58): error TS2339: Property 'googleMap' does not exist on type 'GoogleMapService'.
src/app/services/direction.service.ts(157,44): error TS2339: Property 'googleMap' does not exist on type 'GoogleMapService'.
src/app/services/direction.service.ts(172,60): error TS2339: Property 'googleMap' does not exist on type 'GoogleMapService'.

**Comment by simonlaustsen** [comment]
Hi, thanks for reaching out!
I'm closing issues as we're already in contact through the support channel.
